nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['^http://localhost:5173$', '^http://35.181.213.37:80']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    allow_credentials: true
    max_age: 3600
  paths:
    '^/api':
      origin_regex: true
      allow_origin: ['^http://localhost:5173$', '^http://35.181.213.37:80']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600
      allow_credentials: true